"""create_users_table

Revision ID: ffdc0a98111c
Revises: 
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=30), nullable=False),
                    sa.Column('full_name', sa.String(
                        length=32), nullable=False),
                    sa.Column('bio', sa.String(
                        length=150), nullable=True),
                    sa.Column('phone_number', sa.String(
                        length=10), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username'),
                    sa.UniqueConstraint('phone_number')



                    )

    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('caption', sa.String(
                        length=2200), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.String(
                        length=2200), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('likes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # op.create_table('friends',
    #                 sa.Column('id', sa.Integer(), nullable=False),
    #                 sa.Column('user_id1', sa.Integer(), nullable=False),
    #                 sa.Column('user_id2', sa.Integer(), nullable=False),
    #                 sa.Column('created_at', sa.DateTime(),
    #                           server_default=sa.text('now()'), nullable=True),
    #                 sa.Column('updated_at', sa.DateTime(), nullable=True),
    #                 sa.ForeignKeyConstraint(['user_id1'], ['users.id'], ),
    #                 sa.ForeignKeyConstraint(['user_id2'], ['users.id'], ),
    #                 sa.PrimaryKeyConstraint('id')
    #                 )
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # op.drop_table('friends')
    op.drop_table('comments')
    op.drop_table('images')
    op.drop_table('users')

    # ### end Alembic commands ###
